version: '3.8'

services:
  app:
    build: .
    container_name: vishop
    restart: always
    ports:
      - '3000:3000'
    command: 'npm run start'

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app
